-- AlterTable
ALTER TABLE "Game" ALTER COLUMN "room" DROP NOT NULL,
ALTER COLUMN "player_one" DROP NOT NULL,
ALTER COLUMN "player_two" DROP NOT NULL,
ALTER COLUMN "times" DROP NOT NULL,
ALTER COLUMN "winner" DROP NOT NULL;
